apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-deployment
  labels:
    app: maven
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
apiVersion: v1
kind: Pod
metadata:
  name: maven-pod
spec:
  containers:
    - name: maven
      image: maven:3.8.3-jdk-11-slim
      command: ["sleep", "infinity"]

